# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# DO NOT EDIT THIS FILE DIRECTLY

PATH="$HOME/bin:$HOME/.local/bin:$PATH"

export PATH="$PATH:$HOME/.gem/ruby/3.0.0/bin:/usr/lib/ruby/gems/3.0.0/bin"

export PATH="$PATH:/usr/bin/vendor_perl"

if [ -n "$WSL_DISTRO_NAME" ]; then
  export PATH="$PATH:/mnt/c/Users/retro/Programs/bin"
  export PATH="$PATH:/mnt/c/Users/retro/AppData/Local/Programs/Microsoft VS Code/bin"
  export PATH="$PATH:/mnt/c/Users/retro/Documents/CodingStuff/scripts/bin"
fi

if [ -n "$WSL_DISTRO_NAME" ]; then
  export LIBGL_ALWAYS_INDIRECT=1
fi
