# DO NOT EDIT THIS FILE DIRECTLY

[ -f ~/.terminalrc ] && source ~/.terminalrc
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
[ -f ~/.profile ] && source ~/.profile

source $HOME/.antigen/antigen.zsh
antigen use oh-my-zsh

antigen theme romkatv/powerlevel10k
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-autosuggestions
autoload -U compinit && compinit

antigen bundle vi-mode

antigen apply

bindkey '^[[3~' delete-char
bindkey -a '^[[3~' delete-char

export KEYTIMEOUT=10
bindkey -M viins 'kj' vi-cmd-mode

bindkey -r '^j'
bindkey '^j' autosuggest-accept # similar to deoplete

autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey '^[[A' up-line-or-beginning-search
bindkey '^[[B' down-line-or-beginning-search
bindkey -M vicmd 'k' up-line-or-beginning-search
bindkey -M vicmd 'j' down-line-or-beginning-search

autoload zmv

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

function fzf-history {
	BUFFER=$( ([ -n "$ZSH_NAME" ] && fc -l 1 || history) | fzf +s --tac | sed -r 's/ *[0-9]*\*? *//' | sed -r 's/\\/\\\\/g' )
}
zle -N fzf-history
bindkey '^k' fzf-history

pasteinit() {
  OLD_SELF_INSERT=${${(s.:.)widgets[self-insert]}[2,3]}
  zle -N self-insert url-quote-magic # I wonder if you'd need `.url-quote-magic`?
}

pastefinish() {
  zle -N self-insert $OLD_SELF_INSERT
}
zstyle :bracketed-paste-magic paste-init pasteinit
zstyle :bracketed-paste-magic paste-finish pastefinish

export EDITOR='emacs'

alias emacs='emacsclient --no-wait -a "" -c'

alias :e="$EDITOR"
alias :q='exit'
alias :wq='exit'

export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

alias ..='cd ..'
alias ...='cd ../../../'
alias ....='cd ../../../../'
alias .....='cd ../../../../'

alias ll='ls -lah'
alias df='df -h'
alias du='du -h'

alias mkdir='mkdir -pv'
mcd() {
    mkdir -p $1
    cd $1
}

alias dotfiles='git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'

alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

if [ -n "$WSL_DISTRO_NAME" ]; then
  alias ffmpeg='/mnt/c/Users/retro/Programs/ffmpeg/bin/ffmpeg.exe -hwaccel auto'
fi
