#!/bin/bash

if command -v apt > /dev/null; then
  echo "installing requirements"
  sudo apt install -y git cowsay fortune-mod lolcat
  sudo snap install --classic emacs
  sudo snap install --classic neovim
fi

function dotfiles {
  git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME $@
}

git clone --bare https://github.com/retrocraft/dotfiles.git $HOME/.dotfiles

dotfiles checkout
if [ $? = 0 ]; then
  echo "dotfiles checked out"
else
  echo "backing up existing dotfiles"
  mkdir -p .dotfiles-backup
  dotfiles checkout 2>&1 | egrep "\s+\." | awk {'print $1'} | xargs -l{} mv {} .dotfiles-backup/{}
fi
dotfiles checkout
dotfiles config status.showUntrackedFiles no
dotfiles submodule init
dotfiles submodule update
echo "dotfiles submodules installed"
~/.fzf/install --completion --key-bindings --no-update-rc

echo "dotfiles installed"
